# Generated by Django 4.2.3 on 2024-10-05 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
