# Generated by Django 4.2.3 on 2024-10-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workouttutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttutorial',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
