# Generated by Django 4.2.3 on 2024-10-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_workouttutorial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='workouttutorial',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
