# Generated by Django 4.2.3 on 2024-10-13 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_plans_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sugar_g', models.IntegerField(default=0)),
                ('fiber_g', models.IntegerField(default=0)),
                ('serving_size_g', models.IntegerField(default=0)),
                ('sodium_mg', models.IntegerField(default=0)),
                ('name', models.IntegerField(default=0)),
                ('potassium_mg', models.IntegerField(default=0)),
                ('fat_saturated_g', models.IntegerField(default=0)),
                ('fat_total_g', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('cholesterol_mg', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('carbohydrates_total_g', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
