# Generated by Django 4.2.3 on 2024-10-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='name',
        ),
    ]
