# Generated by Django 4.2.3 on 2024-10-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_nutrition_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nutrition')),
            ],
        ),
    ]
